/**
 * Copyright © 2018 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 */
package eu.jsentinel.jcustos.processor;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import com.google.testing.compile.JavaFileObjects;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DisplayName("SecuredAnnotationProcessor — wrapper-index writer (V00.73)")
class WrapperIndexWriterTest {

  private static final String INDEX_PATH = "META-INF/jsentinel/generated-wrappers.idx";
  private static final String MARKER = "# generated by jCustos-processor";

  private Compilation compile(JavaFileObject... sources) {
    return Compiler.javac()
        .withProcessors(new SecuredAnnotationProcessor())
        .compile(sources);
  }

  @Test
  @DisplayName("single @Secured class emits one index row with its guarded method")
  void singleSecuredClass_emitsOneIndexEntry() throws IOException {
    JavaFileObject source = JavaFileObjects.forSourceLines(
        "demo.DocService",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "",
        "@Secured",
        "public class DocService {",
        "    @RequiresPermission(\"doc:delete\")",
        "    public void delete(final String id) {}",
        "}");

    Compilation result = compile(source);
    assertThat(result).succeeded();

    String content = readIndex(result);
    assertNotNull(content, "index file expected");
    assertTrue(content.startsWith(MARKER + "\n"), "marker comment expected at top");

    List<String> rows = dataRows(content);
    assertEquals(1, rows.size(), "exactly one data row expected");
    assertEquals("demo.DocService:demo.DocServiceSecured:proxybuilder:00.11.00:delete:secured",
        rows.get(0));
  }

  @Test
  @DisplayName("two @Secured classes emit two rows sorted by sourceFqn")
  void twoSecuredClasses_emitSortedRows() throws IOException {
    JavaFileObject a = JavaFileObjects.forSourceLines(
        "demo.Zebra",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "@Secured public class Zebra {",
        "  @RequiresPermission(\"z:read\") public void z() {}",
        "}");
    JavaFileObject b = JavaFileObjects.forSourceLines(
        "demo.Alpha",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "@Secured public class Alpha {",
        "  @RequiresPermission(\"a:read\") public void a() {}",
        "}");

    Compilation result = compile(a, b);
    assertThat(result).succeeded();

    List<String> rows = dataRows(readIndex(result));
    assertEquals(2, rows.size());
    assertTrue(rows.get(0).startsWith("demo.Alpha:"),
        "Alpha must sort before Zebra; got: " + rows);
    assertTrue(rows.get(1).startsWith("demo.Zebra:"));
  }

  @Test
  @DisplayName("compiling the same source twice produces byte-identical index files")
  void incrementalRebuild_isIdempotent() throws IOException {
    JavaFileObject source = JavaFileObjects.forSourceLines(
        "demo.Foo",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "@Secured public class Foo {",
        "  @RequiresPermission(\"f:do\") public void doIt() {}",
        "}");

    String first = readIndex(compile(source));
    String second = readIndex(compile(source));
    assertEquals(first, second, "two independent compilations must produce identical index bytes");
  }

  @Test
  @DisplayName("marker comment is always present")
  void markerCommentIsPresent() throws IOException {
    JavaFileObject source = JavaFileObjects.forSourceLines(
        "demo.Bar",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "@Secured public class Bar {",
        "  @RequiresPermission(\"b:do\") public void doIt() {}",
        "}");
    String content = readIndex(compile(source));
    assertTrue(content.split("\n")[0].equals(MARKER));
  }

  @Test
  @DisplayName("a compilation with no @Secured classes does not produce an index file")
  void noSecuredClasses_emitsNoIndexFile() {
    JavaFileObject source = JavaFileObjects.forSourceLines(
        "demo.Plain",
        "package demo;",
        "public class Plain { public void open() {} }");

    Compilation result = compile(source);
    assertThat(result).succeeded();
    Optional<JavaFileObject> index = result.generatedFile(
        StandardLocation.CLASS_OUTPUT, INDEX_PATH);
    assertFalse(index.isPresent(),
        "no @Secured input → no index file expected");
  }

  @Test
  @DisplayName("methods without a security annotation are omitted from the index row")
  void onlyGuardedMethodsAreIndexed() throws IOException {
    JavaFileObject source = JavaFileObjects.forSourceLines(
        "demo.Mixed",
        "package demo;",
        "import eu.jsentinel.jcustos.authorization.annotations.Secured;",
        "import eu.jsentinel.jcustos.authorization.annotations.RequiresPermission;",
        "@Secured public class Mixed {",
        "  @RequiresPermission(\"m:do\") public void guarded() {}",
        "  public void open() {}",
        "}");

    Compilation result = compile(source);
    assertThat(result).succeeded();
    List<String> rows = dataRows(readIndex(result));
    assertEquals(1, rows.size());
    // method list is in position 5; guarded only
    // V00.74: the sixth :kind suffix is now present; split with limit 6.
    String[] parts = rows.get(0).split(":", 6);
    assertEquals("guarded", parts[4]);
    assertEquals("secured", parts[5]);
  }

  // ── helpers ──────────────────────────────────────────────────────

  private static String readIndex(Compilation compilation) throws IOException {
    Optional<JavaFileObject> opt = compilation.generatedFile(
        StandardLocation.CLASS_OUTPUT, INDEX_PATH);
    assertTrue(opt.isPresent(), "expected " + INDEX_PATH + " in compilation output");
    return readContent(opt.get());
  }

  private static String readContent(JavaFileObject file) throws IOException {
    try (InputStream in = file.openInputStream()) {
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    }
  }

  private static List<String> dataRows(String content) {
    return content.lines()
        .filter(l -> !l.isBlank())
        .filter(l -> !l.startsWith("#"))
        .toList();
  }
}
