/**
 * Copyright © 2017 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package com.svenruppert.jsentinel.standalone;

import com.svenruppert.jsentinel.authorization.api.AccessDeniedException;
import com.svenruppert.jsentinel.authorization.api.JSentinelEnforcer;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.Arrays;

/**
 * Builds a dynamic-proxy wrapper around any interface so that every
 * invocation routes through {@link JSentinelEnforcer}: if the method (or
 * its declaring class) carries a security annotation, the matching
 * evaluator runs before the call is delegated to the real
 * implementation. Denied decisions raise {@link AccessDeniedException};
 * granted decisions fall through.
 *
 * <p>Runtime sibling of the compile-time path: classes annotated with
 * {@link com.svenruppert.jsentinel.authorization.annotations.Secured}
 * get a {@code <Type>Secured} subclass generated by
 * {@code security-processor}. Both paths share the same
 * {@link JSentinelEnforcer} so the rules are consistent.
 *
 * <p>Subject resolution: the proxy reads the current subject through the
 * application's
 * {@link com.svenruppert.jsentinel.authentication.AuthenticationService}
 * + {@link com.svenruppert.jsentinel.authorization.api.SubjectStore},
 * and assembles a {@link com.svenruppert.jsentinel.authorization.api.JSentinelSubject}
 * on the fly via the configured
 * {@link com.svenruppert.jsentinel.authorization.api.AuthorizationService}.
 *
 * <p>Usage:
 * <pre>
 * MyService secured = SecuredProxy.wrap(MyService.class, new MyServiceImpl());
 * secured.deleteDocument(id);  // throws AccessDeniedException if not allowed
 * </pre>
 */
public final class SecuredProxy {

  private SecuredProxy() {
  }

  /**
   * Wraps {@code delegate} in a dynamic proxy that enforces the security
   * annotations declared on {@code interfaceType} (class-level or per
   * method).
   *
   * @param interfaceType the interface the proxy implements
   * @param delegate      the real implementation
   * @param <T>           the interface type
   * @return a proxy implementing {@code interfaceType}
   */
  @SuppressWarnings("unchecked")
  public static <T> T wrap(Class<T> interfaceType, T delegate) {
    if (!interfaceType.isInterface()) {
      throw new IllegalArgumentException(
          "SecuredProxy.wrap requires an interface; got: " + interfaceType.getName());
    }
    return (T) Proxy.newProxyInstance(
        interfaceType.getClassLoader(),
        new Class<?>[]{interfaceType},
        (proxy, method, args) -> {
          // R007: handle Object methods on the proxy's own identity rather
          // than delegating them to the wrapped impl. Delegating breaks the
          // equals/hashCode contract (proxy.equals(proxy) could be false,
          // proxy.equals(delegate) true) and leaks the impl's toString —
          // both make the proxy unusable as a HashMap/HashSet key.
          if (method.getDeclaringClass() == Object.class) {
            return switch (method.getName()) {
              case "equals" -> proxy == (args == null ? null : args[0]);
              case "hashCode" -> System.identityHashCode(proxy);
              case "toString" -> "SecuredProxy<" + interfaceType.getName()
                  + ">@" + Integer.toHexString(System.identityHashCode(proxy));
              // getClass/notify/wait are final and never reach an
              // InvocationHandler; any other Object method delegates safely.
              default -> invokeDelegate(method, delegate, args);
            };
          }
          JSentinelEnforcer.enforce(method, interfaceType);
          return invokeDelegate(method, delegate, args);
        });
  }

  /**
   * Invokes {@code method} on {@code delegate}, unwrapping a reflective
   * {@link InvocationTargetException} so callers see the real cause instead
   * of the reflection wrapper (R007 — applied on both the guarded and the
   * Object-method dispatch paths).
   */
  private static Object invokeDelegate(Method method, Object delegate, Object[] args)
      throws Throwable {
    try {
      return method.invoke(delegate, args);
    } catch (InvocationTargetException ite) {
      throw ite.getCause();
    }
  }

  /**
   * Single-shot check on the calling method. Useful when an interface
   * isn't a clean fit (callbacks, lambdas) but the application still
   * wants to enforce {@code @RequiresPermission} / {@code @RequiresRole}
   * declaratively.
   *
   * <p>Pass {@code MyClass.class} and a method name; the enforcer picks
   * up class-level or method-level annotations and throws on a denied
   * decision.
   *
   * @param ownerClass the class declaring the method
   * @param methodName the method name (overloads ignored — first match)
   * @throws AccessDeniedException if the evaluator rejects the call
   */
  public static void requireAllowed(Class<?> ownerClass, String methodName) {
    Method method = Arrays.stream(ownerClass.getDeclaredMethods())
        .filter(m -> m.getName().equals(methodName))
        .findFirst()
        .orElseThrow(() -> new IllegalArgumentException(
            "No method named '" + methodName + "' on " + ownerClass.getName()));
    JSentinelEnforcer.enforce(method, ownerClass);
  }
}
