/**
 * Copyright © 2018 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 */
package com.svenruppert.vaadin.security.dx.diagnostics;


import java.util.List;
import java.util.Objects;

/**
 * Placeholder shape for one wrapper generated by {@code security-processor}.
 * Real population is implemented in Prompt 020 / 021.
 *
 * @since 00.72.00
 */
public record GeneratedJSentinelWrapper(
    Class<?> sourceType,
    Class<?> generatedType,
    String processor,
    String proxyBuilderVersion,
    List<String> delegatedMethods) {

  public GeneratedJSentinelWrapper {
    Objects.requireNonNull(sourceType, "sourceType");
    Objects.requireNonNull(generatedType, "generatedType");
    Objects.requireNonNull(processor, "processor");
    Objects.requireNonNull(proxyBuilderVersion, "proxyBuilderVersion");
    Objects.requireNonNull(delegatedMethods, "delegatedMethods");
    delegatedMethods = List.copyOf(delegatedMethods);
  }
}
