/**
 * Copyright © 2017 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package com.svenruppert.vaadin.security.authorization.api;

import com.svenruppert.vaadin.security.authorization.api.permissions.HasPermissions;
import com.svenruppert.vaadin.security.authorization.api.permissions.PermissionMatcher;
import com.svenruppert.vaadin.security.authorization.api.permissions.PermissionName;
import com.svenruppert.vaadin.security.authorization.api.roles.HasRoles;
import com.svenruppert.vaadin.security.authorization.api.roles.RoleMatcher;
import com.svenruppert.vaadin.security.authorization.api.roles.RoleName;
import com.svenruppert.vaadin.security.authorization.impl.AnnotationAccessEvaluatorPair;
import com.svenruppert.vaadin.security.authorization.impl.SecurityAnnotationScanner;
import com.svenruppert.vaadin.security.authorization.navigation.AccessContext;
import com.svenruppert.vaadin.security.authorization.navigation.AccessDecision;
import com.svenruppert.vaadin.security.policy.api.PolicyContext;
import com.svenruppert.vaadin.security.policy.api.PolicyDecision;
import com.svenruppert.vaadin.security.policy.spi.PolicyRegistry;

import java.lang.annotation.Annotation;
import java.lang.reflect.AnnotatedElement;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Central enforcement entry point shared by the
 * {@code SecuredProxy} dynamic-proxy path in {@code security-standalone}
 * and the wrapper classes generated by the {@code security-processor}
 * annotation processor. Both paths translate denied decisions into an
 * {@link AccessDeniedException}; granted decisions fall through to the
 * delegate / super call.
 *
 * <p>Two API surfaces:
 * <ul>
 *   <li><strong>Generic</strong>:
 *       {@link #enforce(AnnotatedElement, Class, String)} — reads the
 *       method-security annotation at runtime, instantiates the
 *       configured evaluator and routes the resulting decision.
 *       Used by the dynamic-proxy path where the annotation set is
 *       only known at call time.
 *   </li>
 *   <li><strong>Explicit</strong>: {@link #requirePermission(String)},
 *       {@link #requireAllPermissions(String...)},
 *       {@link #requireAnyPermission(String...)},
 *       {@link #requireRole(String)}, {@link #requireAnyRole(String...)},
 *       {@link #requirePolicy(String)} — for the annotation-processor
 *       path where the constraint is already known at compile time and
 *       can be expanded inline.</li>
 * </ul>
 *
 * <p>All entry points read the current subject through
 * {@link SubjectStores#subjectStore()} and resolve roles / permissions
 * via {@link SecurityServiceResolver#authorizationService()}.
 */
public final class SecurityEnforcer {

  private static final SecurityAnnotationScanner SCANNER = new SecurityAnnotationScanner();

  private SecurityEnforcer() {
  }

  // ── Generic API ─────────────────────────────────────────────────

  /**
   * Reads the security annotation on the supplied {@code methodOrElement}
   * (or its {@code declaringClass} as fallback), evaluates the configured
   * evaluator, and throws {@link AccessDeniedException} when the decision
   * is not {@code Granted}. No-op when no security annotation is present.
   *
   * @param methodOrElement annotated method (typically) or any annotated
   *                        element to inspect first
   * @param declaringClass  declaring class used as fallback element and
   *                        as the {@code resourceName} of the access
   *                        context
   * @param methodName      method name used as the {@code operation} of
   *                        the access context
   * @throws AccessDeniedException when access is denied
   */
  public static void enforce(AnnotatedElement methodOrElement,
                             Class<?> declaringClass,
                             String methodName) {
    Optional<AnnotationAccessEvaluatorPair<Annotation>> match = SCANNER.scan(methodOrElement)
        .or(() -> SCANNER.scan(declaringClass));
    if (match.isEmpty()) {
      return;
    }
    AnnotationAccessEvaluatorPair<Annotation> pair = match.get();
    AccessContext context = newContext(declaringClass, methodName);

    Object evaluator = instantiate(pair.evaluatorClass());
    AuthorizationDecision decision = evaluate(evaluator, context, pair.annotation());
    handle(decision);
  }

  /**
   * Convenience overload that uses {@code method} both as the annotated
   * element and to derive the method name.
   *
   * @param method         annotated method
   * @param declaringClass declaring class
   * @throws AccessDeniedException when access is denied
   */
  public static void enforce(Method method, Class<?> declaringClass) {
    enforce(method, declaringClass, method.getName());
  }

  // ── Explicit API (annotation-processor friendly) ────────────────

  /**
   * Asserts the current subject holds the given permission.
   *
   * @param permission the required permission name
   * @throws AccessDeniedException when no subject is bound or the
   *                               permission is missing
   */
  public static void requirePermission(String permission) {
    requireAllPermissions(permission);
  }

  /**
   * Asserts the current subject holds every listed permission.
   *
   * @param permissions the required permission names; at least one
   * @throws AccessDeniedException when no subject is bound or any
   *                               permission is missing
   */
  public static void requireAllPermissions(String... permissions) {
    if (permissions == null || permissions.length == 0) {
      throw new IllegalArgumentException("permissions must not be empty");
    }
    Set<PermissionName> required = Arrays.stream(permissions)
        .map(PermissionName::new)
        .collect(Collectors.toUnmodifiableSet());
    Set<PermissionName> held = currentPermissions();
    if (!PermissionMatcher.containsAll(held, required)) {
      throw new AccessDeniedException("Missing required permission(s): "
          + String.join(", ", permissions));
    }
  }

  /**
   * Asserts the current subject holds at least one of the listed
   * permissions.
   *
   * @param permissions candidate permission names; at least one
   * @throws AccessDeniedException when no subject is bound or none of
   *                               the candidate permissions is held
   */
  public static void requireAnyPermission(String... permissions) {
    if (permissions == null || permissions.length == 0) {
      throw new IllegalArgumentException("permissions must not be empty");
    }
    Set<PermissionName> candidates = Arrays.stream(permissions)
        .map(PermissionName::new)
        .collect(Collectors.toUnmodifiableSet());
    Set<PermissionName> held = currentPermissions();
    if (!PermissionMatcher.containsAny(held, candidates)) {
      throw new AccessDeniedException("None of the candidate permissions held: "
          + String.join(", ", permissions));
    }
  }

  /**
   * Asserts the current subject holds the given role (role-hierarchy
   * implications are honored).
   *
   * @param role the required role name
   * @throws AccessDeniedException when no subject is bound or the role
   *                               is missing
   */
  public static void requireRole(String role) {
    requireAnyRole(role);
  }

  /**
   * Asserts the current subject holds at least one of the listed roles
   * (role-hierarchy implications are honored).
   *
   * @param roles candidate role names; at least one
   * @throws AccessDeniedException when no subject is bound or none of
   *                               the candidate roles is held
   */
  public static void requireAnyRole(String... roles) {
    if (roles == null || roles.length == 0) {
      throw new IllegalArgumentException("roles must not be empty");
    }
    Set<RoleName> candidates = Arrays.stream(roles)
        .map(RoleName::new)
        .collect(Collectors.toUnmodifiableSet());
    Set<RoleName> held = currentRoles();
    if (!RoleMatcher.containsAnyImplied(held, candidates,
        SecurityServiceResolver.roleHierarchy())) {
      throw new AccessDeniedException("None of the candidate roles held: "
          + String.join(", ", roles));
    }
  }

  /**
   * Asserts the named policy admits the current subject for the supplied
   * resource type / operation.
   *
   * @param policyName     the registered policy name
   * @param resourceType   adapter-neutral resource type
   * @param resourceName   adapter-neutral resource name
   * @param operation      requested operation
   * @throws AccessDeniedException when no subject is bound, the policy
   *                               is unknown, or evaluation does not
   *                               return {@code Allowed}
   */
  public static void requirePolicy(String policyName,
                                   String resourceType,
                                   String resourceName,
                                   String operation) {
    AccessContext access = new AccessContext(
        currentSubject(),
        resourceType,
        resourceName,
        operation,
        Map.of());
    PolicyContext context = new PolicyContext(access, policyName);
    PolicyRegistry registry = SecurityServiceResolver.policyRegistry();
    PolicyDecision decision = registry.evaluate(policyName, context);
    switch (decision) {
      case PolicyDecision.Allowed ignored -> { /* fall through */ }
      case PolicyDecision.Denied denied ->
          throw new AccessDeniedException("Policy '" + policyName + "' denied: " + denied.reason());
      case PolicyDecision.StepUpRequired stepUp ->
          throw new AccessDeniedException("Policy '" + policyName
              + "' requires step-up: method=" + stepUp.method()
              + (stepUp.reason().isEmpty() ? "" : ", reason=" + stepUp.reason()));
    }
  }

  /**
   * Convenience overload using {@code "method"} as resource type and
   * {@code "invoke"} as operation. Suitable for the annotation-processor
   * path that has no domain-specific context.
   *
   * @param policyName the registered policy name
   * @throws AccessDeniedException when access is denied
   */
  public static void requirePolicy(String policyName) {
    requirePolicy(policyName, "method", policyName, "invoke");
  }

  // ── Helpers ─────────────────────────────────────────────────────

  private static AccessContext newContext(Class<?> declaringClass, String methodName) {
    return new AccessContext(
        currentSubject(),
        "method",
        declaringClass.getSimpleName(),
        methodName,
        Map.of());
  }

  @SuppressWarnings({"rawtypes", "unchecked"})
  static Optional<SecuritySubject> currentSubject() {
    Class<?> subjectType = SecurityServiceResolver
        .<Object, Object>authenticationService()
        .subjectType();
    if (subjectType == null) {
      return Optional.empty();
    }
    Class raw = subjectType;
    Optional<Object> raw0 = SubjectStores.subjectStore().currentSubject(raw);
    if (raw0.isEmpty()) {
      return Optional.empty();
    }
    Object user = raw0.get();
    var auth = SecurityServiceResolver.<Object>authorizationService();
    HasRoles roles = auth.rolesFor(user);
    HasPermissions perms = auth.permissionsFor(user);
    return Optional.of(new SecuritySubject(
        user.toString(),
        user.toString(),
        Set.copyOf(roles.roleNames()),
        Set.copyOf(perms.permissionNames())));
  }

  private static Set<PermissionName> currentPermissions() {
    return currentSubject()
        .map(SecuritySubject::permissionNames)
        .orElseThrow(() -> new AccessDeniedException("No authenticated subject"));
  }

  private static Set<RoleName> currentRoles() {
    return currentSubject()
        .map(SecuritySubject::roleNames)
        .orElseThrow(() -> new AccessDeniedException("No authenticated subject"));
  }

  @SuppressWarnings("unchecked")
  private static AuthorizationDecision evaluate(Object evaluator,
                                                AccessContext context,
                                                Annotation annotation) {
    if (evaluator instanceof AuthorizationEvaluator<?> aze) {
      return ((AuthorizationEvaluator<Annotation>) aze).evaluate(context, annotation);
    }
    if (evaluator instanceof AccessEvaluator<?> ae) {
      AccessDecision legacy = ((AccessEvaluator<Annotation>) ae).evaluate(context, annotation);
      return switch (legacy) {
        case AccessDecision.Granted ignored -> AuthorizationDecision.granted();
        case AccessDecision.Reroute r ->
            AuthorizationDecision.forbidden("Reroute requested to " + r.target());
        case AccessDecision.RerouteToError err ->
            AuthorizationDecision.forbidden(err.message() == null ? "Access denied" : err.message());
        case AccessDecision.RerouteWithParameter<?> r ->
            AuthorizationDecision.forbidden("Reroute requested to " + r.target());
        case AccessDecision.RerouteWithParameters<?> r ->
            AuthorizationDecision.forbidden("Reroute requested to " + r.target());
      };
    }
    throw new IllegalStateException(
        "Unsupported evaluator type: " + evaluator.getClass().getName());
  }

  private static void handle(AuthorizationDecision decision) {
    switch (decision) {
      case AuthorizationDecision.Granted ignored -> { /* fall through */ }
      case AuthorizationDecision.Unauthenticated u ->
          throw new AccessDeniedException("Unauthenticated: " + u.reason());
      case AuthorizationDecision.Forbidden f ->
          throw new AccessDeniedException(f.reason());
      case AuthorizationDecision.StepUpRequired stepUp ->
          throw new AccessDeniedException("Step-up required: method=" + stepUp.method()
              + (stepUp.reason().isEmpty() ? "" : ", reason=" + stepUp.reason()));
    }
  }

  private static Object instantiate(Class<?> evaluatorClass) {
    try {
      return evaluatorClass.getDeclaredConstructor().newInstance();
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException(
          "Could not instantiate evaluator " + evaluatorClass.getName(), e);
    }
  }
}
