/**
 * Copyright © 2018 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 */
package com.svenruppert.jsentinel.autoservice.processor;

import com.svenruppert.jsentinel.autoservice.api.JSentinelAutoService;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.NestingKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Compile-time processor that converts {@link JSentinelAutoService}
 * annotations into {@code META-INF/services/<spi-fqn>} entries.
 * <p>
 * Behaviour (V00.72 Prompts 010-013, combined):
 * <ul>
 *   <li>Single- and multi-SPI registrations.</li>
 *   <li>Validation: assignability, no-arg constructor, top-level or
 *       static-nested only, no abstract classes, public SPI types.</li>
 *   <li>Incremental-build safety: a marker comment identifies
 *       processor-authored entries; hand-written entries are preserved
 *       across rounds.</li>
 *   <li>Deterministic output: entries are sorted alphabetically.</li>
 *   <li>No external library, no reflective class loading.</li>
 * </ul>
 *
 * @since 00.72.00
 */
@SupportedAnnotationTypes("com.svenruppert.jsentinel.autoservice.api.JSentinelAutoService")
@SupportedSourceVersion(SourceVersion.RELEASE_26)
public final class JSentinelAutoServiceProcessor extends AbstractProcessor {

  /** Marker comment line; entries below this in a file are considered processor-authored. */
  static final String MARKER =
      "# generated by com.svenruppert.jsentinel.autoservice.processor.JSentinelAutoServiceProcessor";

  /** spi-fqn -> sorted set of impl FQNs accumulated during the build. */
  private final Map<String, Set<String>> generated = new LinkedHashMap<>();

  /**
   * resource-path -> hand-written entries read from a pre-existing file.
   * R032: populated during regular (non-{@code processingOver}) rounds so the
   * read is decoupled from the {@code createResource} write that happens in
   * {@code processingOver} — reading a resource and creating it are kept in
   * separate rounds, avoiding the same-round Filer read/write footgun.
   */
  private final Map<String, Set<String>> handWrittenByResource = new LinkedHashMap<>();

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    Messager messager = processingEnv.getMessager();
    Filer filer = processingEnv.getFiler();

    for (Element element : roundEnv.getElementsAnnotatedWith(JSentinelAutoService.class)) {
      if (!(element instanceof TypeElement impl)) {
        messager.printMessage(Diagnostic.Kind.ERROR,
            "@JSentinelAutoService is only valid on type declarations.", element);
        continue;
      }
      if (!validate(impl, messager)) {
        continue;
      }
      List<String> spiFqns = readSpiFqns(impl, messager);
      if (spiFqns.isEmpty()) {
        continue;
      }
      String implFqn = processingEnv.getElementUtils().getBinaryName(impl).toString();
      for (String spiFqn : spiFqns) {
        generated.computeIfAbsent(spiFqn, k -> new TreeSet<>()).add(implFqn);
      }
    }

    if (!roundEnv.processingOver()) {
      // R032: read pre-existing hand-written entries once, BEFORE the
      // processingOver write round, so getResource and createResource never
      // touch the same path in the same round.
      for (String spiFqn : generated.keySet()) {
        handWrittenByResource.computeIfAbsent(
            "META-INF/services/" + spiFqn,
            path -> readHandWrittenSafely(filer, path));
      }
    } else {
      writeAllResources(filer, messager);
    }
    return true;
  }

  // ---- validation ---------------------------------------------------------

  private boolean validate(TypeElement impl, Messager messager) {
    if (impl.getModifiers().contains(Modifier.ABSTRACT)) {
      error(messager, impl, "autoservice/abstract",
          "abstract type cannot be a ServiceLoader provider",
          "Make the class non-abstract or remove @JSentinelAutoService.");
      return false;
    }
    // R032: a non-public impl yields a services entry that ServiceLoader cannot
    // instantiate at runtime (it needs an accessible public provider). Catch it
    // at compile time, mirroring the existing autoservice/non-public-spi check.
    if (!impl.getModifiers().contains(Modifier.PUBLIC)) {
      error(messager, impl, "autoservice/non-public-impl",
          "non-public type cannot be instantiated by ServiceLoader",
          "Make the class public.");
      return false;
    }
    NestingKind nesting = impl.getNestingKind();
    if (nesting == NestingKind.LOCAL || nesting == NestingKind.ANONYMOUS) {
      error(messager, impl, "autoservice/non-static-nested",
          "local/anonymous types cannot be ServiceLoader providers",
          "Move the class to top level or a static nested type.");
      return false;
    }
    if (nesting == NestingKind.MEMBER && !impl.getModifiers().contains(Modifier.STATIC)) {
      error(messager, impl, "autoservice/non-static-nested",
          "non-static nested type cannot be a ServiceLoader provider",
          "Add 'static' or move to top level.");
      return false;
    }
    if (!hasPublicNoArgConstructor(impl)) {
      error(messager, impl, "autoservice/missing-no-arg-ctor",
          "no public no-arg constructor found",
          "Add a public no-arg constructor.");
      return false;
    }
    return true;
  }

  private boolean hasPublicNoArgConstructor(TypeElement impl) {
    for (Element member : impl.getEnclosedElements()) {
      if (member.getKind() == ElementKind.CONSTRUCTOR
          && member.getModifiers().contains(Modifier.PUBLIC)) {
        if (((ExecutableElement) member).getParameters().isEmpty()) {
          return true;
        }
      }
    }
    // If no constructor is declared, the default public no-arg constructor is synthesized
    // — but only if the class itself is public AND has no other constructors.
    boolean hasAnyCtor = impl.getEnclosedElements().stream()
        .anyMatch(e -> e.getKind() == ElementKind.CONSTRUCTOR);
    return !hasAnyCtor && impl.getModifiers().contains(Modifier.PUBLIC);
  }

  private List<String> readSpiFqns(TypeElement impl, Messager messager) {
    List<String> spiFqns = new ArrayList<>();
    for (AnnotationMirror am : impl.getAnnotationMirrors()) {
      if (!am.getAnnotationType().toString().equals(JSentinelAutoService.class.getName())) {
        continue;
      }
      for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry :
          am.getElementValues().entrySet()) {
        if (!"value".equals(entry.getKey().getSimpleName().toString())) {
          continue;
        }
        Object raw = entry.getValue().getValue();
        if (raw instanceof List<?> items) {
          for (Object item : items) {
            if (item instanceof AnnotationValue av && av.getValue() instanceof TypeMirror tm) {
              addSpi(impl, tm, spiFqns, messager);
            }
          }
        } else if (raw instanceof TypeMirror tm) {
          addSpi(impl, tm, spiFqns, messager);
        }
      }
    }
    return spiFqns;
  }

  private void addSpi(TypeElement impl, TypeMirror spi, List<String> out, Messager messager) {
    Element spiEl = processingEnv.getTypeUtils().asElement(spi);
    if (!(spiEl instanceof TypeElement spiType)) {
      error(messager, impl, "autoservice/spi-not-a-type",
          "Declared SPI is not a class or interface: " + spi,
          "Use a public class or interface as the SPI.");
      return;
    }
    if (!spiType.getModifiers().contains(Modifier.PUBLIC)) {
      error(messager, impl, "autoservice/non-public-spi",
          "Declared SPI " + spiType + " is not public",
          "Make the SPI type public.");
      return;
    }
    if (!processingEnv.getTypeUtils().isAssignable(impl.asType(), spi)) {
      error(messager, impl, "autoservice/not-assignable",
          impl + " is not assignable to declared SPI " + spiType,
          "Declare the SPI on the class via 'implements' or 'extends'.");
      return;
    }
    String fqn = processingEnv.getElementUtils().getBinaryName(spiType).toString();
    out.add(fqn);
  }

  // ---- file generation ----------------------------------------------------

  private void writeAllResources(Filer filer, Messager messager) {
    for (Map.Entry<String, Set<String>> entry : generated.entrySet()) {
      String resourcePath = "META-INF/services/" + entry.getKey();
      Set<String> newEntries = entry.getValue();

      // R032: hand-written entries were read in an earlier round (decoupled
      // from this write) — no getResource in the same round as createResource.
      Set<String> handWritten = handWrittenByResource.getOrDefault(
          resourcePath, new LinkedHashSet<>());

      try {
        FileObject created = filer.createResource(
            StandardLocation.CLASS_OUTPUT, "", resourcePath);
        try (Writer w = created.openWriter()) {
          if (!handWritten.isEmpty()) {
            for (String h : handWritten) {
              w.write(h);
              w.write('\n');
            }
            // R032: a mixed file (hand-written + generated) is a supported,
            // benign state — preserved across rounds. NOTE, not WARNING, so a
            // clean build that legitimately merges does not emit a warning.
            messager.printMessage(Diagnostic.Kind.NOTE,
                "autoservice/mixed-file-detected: " + resourcePath
                    + " contains hand-written entries plus processor-generated entries. "
                    + "Consider migrating the hand-written entries to @JSentinelAutoService.");
          }
          w.write(MARKER);
          w.write('\n');
          // Sorted for determinism
          for (String impl : new TreeSet<>(newEntries)) {
            w.write(impl);
            w.write('\n');
          }
        }
        messager.printMessage(Diagnostic.Kind.NOTE,
            "AutoService: wrote " + resourcePath + " with "
                + newEntries.size() + " entr" + (newEntries.size() == 1 ? "y" : "ies"));
      } catch (IOException io) {
        messager.printMessage(Diagnostic.Kind.ERROR,
            "Failed to write " + resourcePath + ": " + io.getMessage());
      }
    }
  }

  /**
   * Reads pre-existing hand-written entries for {@code resourcePath}, returning
   * an empty set when no file exists yet. {@code getResource}/{@code openInputStream}
   * may throw {@link IOException} (real Filers) or a {@link RuntimeException}
   * (in-memory file managers when the resource is absent); both mean
   * "nothing to preserve".
   */
  private Set<String> readHandWrittenSafely(Filer filer, String resourcePath) {
    Set<String> handWritten = new LinkedHashSet<>();
    try {
      FileObject existing = filer.getResource(
          StandardLocation.CLASS_OUTPUT, "", resourcePath);
      readExistingEntries(existing, handWritten);
    } catch (IOException | RuntimeException ignored) {
      // file does not exist yet — nothing to preserve
    }
    return handWritten;
  }

  private void readExistingEntries(FileObject existing, Set<String> handWritten) throws IOException {
    boolean processorAuthoredFromHere = false;
    try (InputStream in = existing.openInputStream();
         BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
      String line;
      while ((line = r.readLine()) != null) {
        if (line.equals(MARKER)) {
          processorAuthoredFromHere = true;
          continue;
        }
        if (line.isBlank()) {
          continue;
        }
        if (processorAuthoredFromHere) {
          // skip — processor will re-emit these from `generated`
          continue;
        }
        if (line.startsWith("#")) {
          // skip comment lines from hand-written portion too (not our marker)
          continue;
        }
        handWritten.add(line.trim());
      }
    }
  }

  private void error(Messager messager, Element element, String code, String detail, String fix) {
    messager.printMessage(Diagnostic.Kind.ERROR,
        "@JSentinelAutoService on " + element + ": " + detail
            + ". Suggested fix: " + fix + ". Code: " + code,
        element);
  }
}
