/**
 * Copyright © 2018 Sven Ruppert (sven.ruppert@gmail.com)
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 */
package com.svenruppert.jsentinel.dx.diagnostics;

/**
 * Single source of truth for the {@code generated-wrappers.idx} file
 * format shared by {@link WrapperIndexReader} (in {@code security-dx})
 * and the writer in {@code security-processor}.
 *
 * <p>The writer in {@code security-processor} cannot reference this
 * package-private class across modules; it duplicates the same literal
 * constants and matches them by value. Keep both in sync.
 *
 * @since 00.73.00
 */
final class WrapperIndexFormat {

  /** Resource path of the index file on the classpath. */
  static final String RESOURCE_PATH = "META-INF/jsentinel/generated-wrappers.idx";

  /** Marker comment that opens the index file. Lines starting with {@code #} are ignored by the reader. */
  static final String MARKER_COMMENT = "# generated by security-for-flow security-processor";

  /** Field separator between the five top-level fields. */
  static final String FIELD_SEPARATOR = ":";

  /** Separator between method names in the fifth field. */
  static final String METHOD_SEPARATOR = ",";

  private WrapperIndexFormat() {
    throw new AssertionError("no instances");
  }
}
