# jSentinel custom license repository for the org.codehaus.mojo:license-maven-plugin file resolver.
#
# This (intentionally empty) properties file exists ONLY so the plugin's file
# resolver (file://${project.basedir}/src/license) does not abort the build with
# "could not obtain the license repository: no licenses.properties found".
# The actual `eupl_v1_1` license that the process-sources `update-file-header`
# execution uses is resolved from the plugin's BUILT-IN classpath repository
# (META-INF/licenses/eupl_v1_1), so no license text is needed here.
#
# Do NOT delete this file: without it every build fails at process-sources.
# It is tracked in git as of V00.79.40 — it was previously a local, untracked
# file that went missing between sessions and broke the build (which then had to
# run with -Dlicense.skipUpdateLicense=true). See RELEASE-NOTES-00.79.40 build note.
